name: assets-test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - assets/**
    types:
      - opened
      - labeled
      - synchronize
      - reopened

defaults:
  run:
    shell: bash

jobs:
  check-execution-context:
    uses: tea553/repo0/.github/workflows/check-execution-context.yaml@main

  setup:
    name: Set up tests
    if: fromJSON(needs.check-execution-context.outputs.continue)
    runs-on: ubuntu-latest
    needs: check-execution-context
    environment: Testing

    permissions:
      contents: read
    
    steps:
      - name: Clone branch
        uses: tea553/repo0/.github/actions/clone-repo@main
        with:
          forked-pr: ${{ needs.check-execution-context.outputs.forked_pr }}
          fetch-depth: 2
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_separator: ','
          separator: ','
          sha: ${{ env.merge_commit_hash || github.sha }}

      - name: Use Python 3.8 or newer
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.8'
    
      - name: Create test matrix for changed assets
        id: create-test-matrix
        run: python -c "${{ steps.changed-files.outputs.all_modified_files }}"
